export const config = [
  {
    title: 'whiteNoise',
    apiSuggestions: ['whitenoise'],
    titleSuggestions: ['soothing', 'noise'],
    category: 'Soundscapes',
  },
  {
    title: 'morning',
    apiSuggestions: ['morning', 'birds', 'sun'],
    titleSuggestions: ['morning', 'sunrise'],
    category: 'Soundscapes',
  },
  {
    title: 'fire',
    apiSuggestions: ['fire', 'fireplace', 'campfire'],
    titleSuggestions: ['cozy', 'fireplace', 'fire', 'comfy'],
    category: 'Soundscapes',
  },
  {
    title: 'ocean',
    apiSuggestions: ['ocean', 'waves', 'sea'],
    titleSuggestions: ['ocean', 'sea', 'beach', 'lake', 'waves'],
    category: 'Soundscapes',
  },
  {
    title: 'lightRain',
    apiSuggestions: ['light rain', 'drizzle', 'sprinkle'],
    titleSuggestions: ['rain', 'drizzle', 'rainy'],
    category: 'Soundscapes',
  },
  {
    title: 'rain',
    apiSuggestions: ['rain', 'heavy rain', 'storm'],
    titleSuggestions: ['rainy', 'heavy rain', 'rain'],
    category: 'Soundscapes',
  },
  {
    title: 'thunder',
    apiSuggestions: ['thunder', 'thunderstorm', 'lightning'],
    titleSuggestions: ['thunder', 'stormy'],
    category: 'Soundscapes',
  },
  {
    title: 'train',
    apiSuggestions: ['train', 'railroad', 'subway'],
    titleSuggestions: ['train', 'railroad', 'subway', 'voyage', 'journey'],
    category: 'Soundscapes',
  },
  {
    title: 'night',
    apiSuggestions: ['night', 'crickets', 'owl'],
    titleSuggestions: ['night', 'midnight'],
    category: 'Soundscapes',
  },
  {
    title: 'scary',
    apiSuggestions: ['scary', 'horror', 'creepy'],
    titleSuggestions: ['scary', 'eerie', 'creepy'],
    category: 'Soundscapes',
  },
  {
    title: 'crow',
    apiSuggestions: ['crow', 'raven', 'bird'],
    titleSuggestions: ['crow', 'raven'],
    category: 'Soundscapes',
  },
  {
    title: 'chatter',
    apiSuggestions: ['chatter', 'people', 'crowd'],
    titleSuggestions: ['chatter', 'crowd', 'ambience'],
    category: 'Soundscapes',
  },
  {
    title: 'music',
    apiSuggestions: [
      'music',
      'piano',
      'classical',
      'Beethoven',
      'Satie',
      'Chopin',
      'Gnossienne',
      'piano+romantic',
      'calm',
      'sad',
      'melancholic',
      'Gymnopedie No.1',
      'violin',
      'soothing',
      'smooth',
    ],
    titleSuggestions: ['music', 'relaxing', 'music'],
    category: 'music',
    additionalApiFields: '&filter=description:piano',
  },
];
