export const config = [
  {
    title: 'whiteNoise',
    apiSuggestions: ['whitenoise'],
    titleSuggestions: ['soothing', 'noise'],
    category: 'Soundscapes',
  },
  {
    title: 'morning',
    apiSuggestions: ['morning', 'birds', 'sun'],
    titleSuggestions: ['morning', 'sunrise'],
    category: 'Soundscapes',
  },
  {
    title: 'fire',
    apiSuggestions: ['fire', 'fireplace', 'campfire'],
    titleSuggestions: ['cozy', 'fireplace', 'fire', 'comfy'],
    category: 'Soundscapes',
  },
  {
    title: 'ocean',
    apiSuggestions: ['ocean', 'waves', 'sea'],
    titleSuggestions: ['ocean', 'sea', 'beach', 'lake', 'waves'],
    category: 'Soundscapes',
  },
  {
    title: 'lake',
    apiSuggestions: ['ocean', 'waves', 'sea'],
    titleSuggestions: ['lake', 'waves'],
    category: 'Soundscapes',
  },
  {
    title: 'lightRain',
    apiSuggestions: ['light rain', 'drizzle', 'sprinkle'],
    titleSuggestions: ['rain', 'drizzle', 'rainy'],
    category: 'Soundscapes',
  },
  {
    title: 'heavyRain',
    apiSuggestions: ['rain', 'heavy rain', 'storm'],
    titleSuggestions: ['rainy', 'heavy rain', 'rain'],
    category: 'Soundscapes',
  },
  {
    title: 'thunder',
    apiSuggestions: ['thunder', 'thunderstorm', 'lightning'],
    titleSuggestions: ['thunder', 'stormy'],
    category: 'Soundscapes',
  },
  {
    title: 'train',
    apiSuggestions: ['train', 'railroad', 'subway'],
    titleSuggestions: ['train', 'railroad', 'subway', 'voyage', 'journey'],
    category: 'Soundscapes',
  },
  {
    title: 'night',
    apiSuggestions: ['night', 'crickets', 'owl'],
    titleSuggestions: ['night', 'midnight'],
    category: 'Soundscapes',
  },
  {
    title: 'wind',
    apiSuggestions: [],
    titleSuggestions: ['wind'],
    category: 'Soundscapes',
  },
  {
    title: 'scary',
    apiSuggestions: ['scary', 'horror', 'creepy'],
    titleSuggestions: ['scary', 'eerie', 'creepy'],
    category: 'Soundscapes',
  },
  {
    title: 'crow',
    apiSuggestions: ['crow', 'raven', 'bird'],
    titleSuggestions: ['crow', 'raven'],
    category: 'Soundscapes',
  },
  {
    title: 'chatter',
    apiSuggestions: ['chatter', 'people', 'crowd'],
    titleSuggestions: ['chatter', 'crowd', 'ambience'],
    category: 'Soundscapes',
  },
  {
    title: 'bowl',
    apiSuggestions: ['chatter', 'people', 'crowd'],
    titleSuggestions: ['breath', 'bowl'],
    category: 'Soundscapes',
  },
  {
    title: 'music',
    apiSuggestions: [
      501199, 750021, 746982, 706660, 706660, 524327, 747495, 745762, 745828,
      773283, 753505, 706760, 714266, 709984, 547451,
    ],
    titleSuggestions: ['music', 'relaxing', 'music'],
    category: 'music',
    additionalApiFields: '&filter=description:piano',
  },
];
